### ISSUE TITLE
add sorting functionality for title, tag, createdAt, updatedAt using query parameters

### ISSUE THREAD

**Issue by shiyaamsunder** [Gukkey/notesapi#4]
Sample api spec for sorting the results of `getAllNotes`.
`api/v0/notes?sort=createdAt&by=desc`

- [ ] Need decide/finalize the api spec

**Comment by Gukkey** [comment]
@shiyaamsunder let me know if something breaks. Had some level of tests and fixed some things myself, if everything works, I will start optimising the code and make it bit readable.
